version: "3.9" # https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users
    volumes:
      - /.docker/mongodb/weather/data:/data/db
      - /.docker/mongodb/weather/logs:/data/logs
    networks:
      - server-network

  server:
    container_name: weather-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:3000
    restart: on-failure
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - server-network

networks:
  server-network: